gig_list_upcoming_frontend:
    path: /gigs
    defaults: { _controller: 'App\Controller\GigController::listUpcoming' }
gig_list_past_frontend:
    path:
      en: /gigs/past
      de: /gigs/archiv
    defaults: { _controller: 'App\Controller\GigController::listPast' }
gig_show:
    path: /gig/{slug}
    defaults: { _controller: 'App\Controller\GigController::show' }
