gig_list_upcoming_frontend:
    path: /gig
    defaults: { _controller: 'App\Controller\GigController::listUpcoming' }
gig_list_past_frontend:
    path: /gig/past
    defaults: { _controller: 'App\Controller\GigController::listPast' }
gig_show:
    path: /gig/{slug}
    defaults: { _controller: 'App\Controller\GigController::show' }
