menu_main_list:
    path: /main-menu
    defaults: { _controller: 'App\Controller\MenuController::listMainMenu' }

menu_main_update:
    path: /main-menu/update
    defaults: { _controller: 'App\Controller\MenuController::updateMainMenu' }
    methods: [POST]
