App\Entity\Menu:
    type: entity
    repositoryClass: App\Repository\MenuRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        type:
            type: string
            length: 100
    oneToMany:
        items:
            targetEntity: MenuItem
            mappedBy: menu

