App\Entity\Page:
    type: entity
    repositoryClass: App\Repository\PageRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 100
        content:
            type: text
    oneToMany:
        items:
            targetEntity: MenuItem
            mappedBy: menu
